// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Lab08Task02.Models
{
    public partial class schoolDbContext : DbContext
    {
        public schoolDbContext()
        {
        }

        public schoolDbContext(DbContextOptions<schoolDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Student> Students { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasKey(e => e.St_Id);

                entity.ToTable("Student");

                entity.Property(e => e.St_Id).ValueGeneratedNever();

                entity.Property(e => e.St_Address).HasMaxLength(100);

                entity.Property(e => e.St_Fname).HasMaxLength(50);

                entity.Property(e => e.St_Lname)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.HasOne(d => d.St_superNavigation)
                    .WithMany(p => p.InverseSt_superNavigation)
                    .HasForeignKey(d => d.St_super)
                    .HasConstraintName("FK_Student_Student");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}